package info.sroman.entity;
// Generated Dec 7, 2018 11:22:01 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * XmlpRptI8 generated by hbm2java
 */
@Entity
@Table(name="XMLP_RPT_I8"
    ,schema="OWNER"
)
public class XmlpRptI8  implements java.io.Serializable {


     private XmlpRptI8Id id;
     private String nmDsplRptXmlp;
     private String ctgRptXmlp;

    public XmlpRptI8() {
    }

	
    public XmlpRptI8(XmlpRptI8Id id) {
        this.id = id;
    }
    public XmlpRptI8(XmlpRptI8Id id, String nmDsplRptXmlp, String ctgRptXmlp) {
       this.id = id;
       this.nmDsplRptXmlp = nmDsplRptXmlp;
       this.ctgRptXmlp = ctgRptXmlp;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idRptXmlp", column=@Column(name="ID_RPT_XMLP", nullable=false, precision=38, scale=0) ), 
        @AttributeOverride(name="lcl", column=@Column(name="LCL", nullable=false, length=10) ) } )
    public XmlpRptI8Id getId() {
        return this.id;
    }
    
    public void setId(XmlpRptI8Id id) {
        this.id = id;
    }
    
    @Column(name="NM_DSPL_RPT_XMLP", length=120)
    public String getNmDsplRptXmlp() {
        return this.nmDsplRptXmlp;
    }
    
    public void setNmDsplRptXmlp(String nmDsplRptXmlp) {
        this.nmDsplRptXmlp = nmDsplRptXmlp;
    }
    
    @Column(name="CTG_RPT_XMLP", length=50)
    public String getCtgRptXmlp() {
        return this.ctgRptXmlp;
    }
    
    public void setCtgRptXmlp(String ctgRptXmlp) {
        this.ctgRptXmlp = ctgRptXmlp;
    }




}


