package info.sroman.entity;
// Generated Dec 7, 2018 11:22:01 PM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import javax.persistence.*;

/**
 * XmlpRptCfgPrmt generated by hbm2java
 */
@Entity
@Table(name="XMLP_RPT_CFG_PRMT"
)
public class XmlpRptCfgPrmt  implements java.io.Serializable {


     private XmlpRptCfgPrmtId id;
     private XmlpRpt xmlpRpt;
     private String nmPrmtCfgRpt;
     private String dftVlCfgRpt;
     private String nmDsplCfgRpt;
     private String tyCfgPrmtRpt;
     private Character flVwCfgRpt;
     private Character flRqCfgRpt;
     private BigDecimal nmbSctnCfgRpt;

    public XmlpRptCfgPrmt() {
    }

	
    public XmlpRptCfgPrmt(XmlpRptCfgPrmtId id, XmlpRpt xmlpRpt) {
        this.id = id;
        this.xmlpRpt = xmlpRpt;
    }
    public XmlpRptCfgPrmt(XmlpRptCfgPrmtId id, XmlpRpt xmlpRpt, String nmPrmtCfgRpt, String dftVlCfgRpt, String nmDsplCfgRpt, String tyCfgPrmtRpt, Character flVwCfgRpt, Character flRqCfgRpt, BigDecimal nmbSctnCfgRpt) {
       this.id = id;
       this.xmlpRpt = xmlpRpt;
       this.nmPrmtCfgRpt = nmPrmtCfgRpt;
       this.dftVlCfgRpt = dftVlCfgRpt;
       this.nmDsplCfgRpt = nmDsplCfgRpt;
       this.tyCfgPrmtRpt = tyCfgPrmtRpt;
       this.flVwCfgRpt = flVwCfgRpt;
       this.flRqCfgRpt = flRqCfgRpt;
       this.nmbSctnCfgRpt = nmbSctnCfgRpt;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idPrmtCfgRpt", column=@Column(name="ID_PRMT_CFG_RPT", nullable=false, precision=38, scale=0) ), 
        @AttributeOverride(name="idRptXmlp", column=@Column(name="ID_RPT_XMLP", nullable=false, precision=38, scale=0) ) } )
    public XmlpRptCfgPrmtId getId() {
        return this.id;
    }
    
    public void setId(XmlpRptCfgPrmtId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.EAGER, cascade = CascadeType.ALL)
    @JoinColumn(name="ID_RPT_XMLP", nullable=false, insertable=false, updatable=false)
    public XmlpRpt getXmlpRpt() {
        return this.xmlpRpt;
    }
    
    public void setXmlpRpt(XmlpRpt xmlpRpt) {
        this.xmlpRpt = xmlpRpt;
    }
    
    @Column(name="NM_PRMT_CFG_RPT", length=80)
    public String getNmPrmtCfgRpt() {
        return this.nmPrmtCfgRpt;
    }
    
    public void setNmPrmtCfgRpt(String nmPrmtCfgRpt) {
        this.nmPrmtCfgRpt = nmPrmtCfgRpt;
    }
    
    @Column(name="DFT_VL_CFG_RPT", length=64)
    public String getDftVlCfgRpt() {
        return this.dftVlCfgRpt;
    }
    
    public void setDftVlCfgRpt(String dftVlCfgRpt) {
        this.dftVlCfgRpt = dftVlCfgRpt;
    }
    
    @Column(name="NM_DSPL_CFG_RPT", length=120)
    public String getNmDsplCfgRpt() {
        return this.nmDsplCfgRpt;
    }
    
    public void setNmDsplCfgRpt(String nmDsplCfgRpt) {
        this.nmDsplCfgRpt = nmDsplCfgRpt;
    }
    
    @Column(name="TY_CFG_PRMT_RPT")
    public String getTyCfgPrmtRpt() {
        return this.tyCfgPrmtRpt;
    }
    
    public void setTyCfgPrmtRpt(String tyCfgPrmtRpt) {
        this.tyCfgPrmtRpt = tyCfgPrmtRpt;
    }
    
    @Column(name="FL_VW_CFG_RPT", length=1)
    public Character getFlVwCfgRpt() {
        return this.flVwCfgRpt;
    }
    
    public void setFlVwCfgRpt(Character flVwCfgRpt) {
        this.flVwCfgRpt = flVwCfgRpt;
    }
    
    @Column(name="FL_RQ_CFG_RPT", length=1)
    public Character getFlRqCfgRpt() {
        return this.flRqCfgRpt;
    }
    
    public void setFlRqCfgRpt(Character flRqCfgRpt) {
        this.flRqCfgRpt = flRqCfgRpt;
    }
    
    @Column(name="NMB_SCTN_CFG_RPT", precision=38, scale=0)
    public BigDecimal getNmbSctnCfgRpt() {
        return this.nmbSctnCfgRpt;
    }
    
    public void setNmbSctnCfgRpt(BigDecimal nmbSctnCfgRpt) {
        this.nmbSctnCfgRpt = nmbSctnCfgRpt;
    }

    @Override
    public String toString() {
        return "XmlpRptCfgPrmt{" +
                "id=" + id +
                ", xmlpRpt=" + xmlpRpt +
                ", nmPrmtCfgRpt='" + nmPrmtCfgRpt + '\'' +
                ", dftVlCfgRpt='" + dftVlCfgRpt + '\'' +
                ", nmDsplCfgRpt='" + nmDsplCfgRpt + '\'' +
                ", tyCfgPrmtRpt='" + tyCfgPrmtRpt + '\'' +
                ", flVwCfgRpt=" + flVwCfgRpt +
                ", flRqCfgRpt=" + flRqCfgRpt +
                ", nmbSctnCfgRpt=" + nmbSctnCfgRpt +
                '}';
    }
}


