package info.sroman.entity;
// Generated Dec 7, 2018 11:22:01 PM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * XmlpRptCfgPrmtId generated by hbm2java
 */
@Embeddable
public class XmlpRptCfgPrmtId  implements java.io.Serializable {


     private BigDecimal idPrmtCfgRpt;
     private BigDecimal idRptXmlp;

    public XmlpRptCfgPrmtId() {
    }

    public XmlpRptCfgPrmtId(BigDecimal idPrmtCfgRpt, BigDecimal idRptXmlp) {
       this.idPrmtCfgRpt = idPrmtCfgRpt;
       this.idRptXmlp = idRptXmlp;
    }
   

    @Column(name="ID_PRMT_CFG_RPT", nullable=false, precision=38, scale=0)
    public BigDecimal getIdPrmtCfgRpt() {
        return this.idPrmtCfgRpt;
    }
    
    public void setIdPrmtCfgRpt(BigDecimal idPrmtCfgRpt) {
        this.idPrmtCfgRpt = idPrmtCfgRpt;
    }

    @Column(name="ID_RPT_XMLP", nullable=false, precision=38, scale=0)
    public BigDecimal getIdRptXmlp() {
        return this.idRptXmlp;
    }
    
    public void setIdRptXmlp(BigDecimal idRptXmlp) {
        this.idRptXmlp = idRptXmlp;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof XmlpRptCfgPrmtId) ) return false;
		 XmlpRptCfgPrmtId castOther = ( XmlpRptCfgPrmtId ) other; 
         
		 return ( (this.getIdPrmtCfgRpt()==castOther.getIdPrmtCfgRpt()) || ( this.getIdPrmtCfgRpt()!=null && castOther.getIdPrmtCfgRpt()!=null && this.getIdPrmtCfgRpt().equals(castOther.getIdPrmtCfgRpt()) ) )
 && ( (this.getIdRptXmlp()==castOther.getIdRptXmlp()) || ( this.getIdRptXmlp()!=null && castOther.getIdRptXmlp()!=null && this.getIdRptXmlp().equals(castOther.getIdRptXmlp()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdPrmtCfgRpt() == null ? 0 : this.getIdPrmtCfgRpt().hashCode() );
         result = 37 * result + ( getIdRptXmlp() == null ? 0 : this.getIdRptXmlp().hashCode() );
         return result;
   }

    @Override
    public String toString() {
        return "XmlpRptCfgPrmtId{" +
                "idPrmtCfgRpt=" + idPrmtCfgRpt +
                ", idRptXmlp=" + idRptXmlp +
                '}';
    }
}


